name: example
description: An example application to demonstrate the usage of your_package.
publish_to: 'none' # This is to prevent the example from being published.
version: 0.1.2+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  custom_build_tool:
    path: ../
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
