name: custom_build_tool
description: A sample command-line application.
version: 1.0.1
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  args: ^2.5.0
  yaml: ^3.1.2
# path: ^1.8.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
