name: custom_build_tool
description: A package for Streamline Version Updates and APK Builds in Flutter Projects.
version: 1.2.18
repository: https://github.com/Moein-dev/custom_build_tool
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.9
  lints: ^3.0.0
  test: ^1.24.0

executables:
  custom_build_tool: custom_build_tool


platforms:
  android:
  ios:  