name: custom_build_tool
description: A pakcage for Streamline Version Updates and APK Builds in Flutter Projects.
version: 1.2.15
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2
# path: ^1.8.0
dev_dependencies:
  build: ^2.4.1
  build_runner: ^2.4.9
  lints: ^3.0.0
  test: ^1.24.0

executables:
  custom_build_tool: bin/custom_build_tool.dart
